---
version: '3'

services:
  code-to-ecr:
    container_name: code-to-ecr
    build:
      context: .
      dockerfile: Dockerfile
    image: dceoy/code-to-ecr:latest
    entrypoint:
      - /usr/local/bin/code-to-ecr
